############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 01/03/2024        #
############################
# Function: This file is used to define the CI/CD pipeline for the project.
image: mcr.microsoft.com/dotnet/sdk:7.0 # Global image for all jobs

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: '*/'

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push

before_script:
  - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'

stages:
  - build
  - test
  - deploy
  - notify

build: # Job to build the solution/projects
  stage: build
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
    - apt-get install -y nodejs
    - 'dotnet build --no-restore'
  only:
    - main # Only notify on the main branch

test: # Job to run the tests
    stage: test
    script:
        - 'dotnet test --no-build'
    only:
      - main # Only notify on the main branch

code_quality: # Job to run the code analysis
  stage: test
  script:
    - 'dotnet build /p:CodeAnalysis=True /p:CodeAnalysisRuleSet=custom.ruleset'
  only:
    - main # Only notify on the main branch

security_scan: # Job to scan the image for vulnerabilities
  stage: test
  script:
    - 'trivy image myapp:latest'
  only:
    - main # Only notify on the main branch

deploy: # Job to deploy the application (temp)
  stage: deploy
  script: echo "Deployment script"
  environment: production
  only:
    - main # Only notify on the main branch
  
notify: # Job to notify the team that the build was successful
  stage: notify
  script:
    - 'echo "Build successful!"'
  when: on_success
  allow_failure: false
  only:
    - main # Only notify on the main branch